name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set short commit SHA
        id: vars
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vinay199/python-app:${{ env.COMMIT_ID }}

    outputs:
      COMMIT_ID: ${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # - name: modify helm values.yaml with new image tag
      #   shell: bash
      #   run: |
      #     sed -i 's|^  tag: .*|  tag: '${{ needs.ci.outputs.COMMIT_ID }}'|' python-app/charts/python-app/values.yaml

      - name: modify helm values.yaml with new image tag
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.COMMIT_ID }}
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.COMMIT_ID }}"' charts/python-app/values.yaml

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update image tag to ${{ needs.ci.outputs.COMMIT_ID }}

      - name: argocd cli installation
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app